apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        environment: staging